# Copyright 2021 The ParallelAccel Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: working_area-api-stop-idling-workers
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-service
              image: REDACTED
              imagePullPolicy: "Always"
              command: ["python3"]
              args: ["cronjob.py"]
              env:
                - name: GCP_PROJECT
                  valueFrom:
                    configMapKeyRef:
                      name: working_area-api-config
                      key: GCP_PROJECT
                - name: GKE_CLUSTER
                  valueFrom:
                    configMapKeyRef:
                      name: working_area-api-config
                      key: GKE_CLUSTER
              envFrom:
                - configMapRef:
                    name: working_area-config
          restartPolicy: OnFailure
